version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/cds
    depends_on:
      - db
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
     - backend

networks:
  backend:
    driver: bridge 

