# Generated by Django 2.2.2 on 2021-01-02 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('telegram_bonus', models.IntegerField(default=50)),
                ('slack_bonus', models.IntegerField(default=50)),
                ('git_bonus', models.IntegerField(default=50)),
                ('project_description', models.TextField(null=True)),
                ('project_team', models.CharField(max_length=255, null=True)),
                ('team_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GithubEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ourplatform.Event')),
                ('type', models.CharField(max_length=255, null=True)),
                ('repo', models.CharField(max_length=255, null=True)),
                ('metaData', models.CharField(max_length=255, null=True)),
            ],
            bases=('ourplatform.event',),
        ),
        migrations.CreateModel(
            name='SlackEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ourplatform.Event')),
                ('message', models.TextField(null=True)),
                ('channel', models.CharField(max_length=255, null=True)),
            ],
            bases=('ourplatform.event',),
        ),
        migrations.CreateModel(
            name='TelegramEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ourplatform.Event')),
                ('message', models.CharField(default='', max_length=255)),
                ('chat', models.CharField(max_length=255, null=True)),
            ],
            bases=('ourplatform.event',),
        ),
        migrations.CreateModel(
            name='ProjectAndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourplatform.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ourplatform_event_related', related_query_name='ourplatform_events', to='ourplatform.Project'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
