# Generated by Django 3.1.2 on 2021-04-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='purchase_status',
            field=models.CharField(choices=[('In Progress', 'In progress'), ('Complete', 'Complete'), ('For Return', 'For Return'), ('Returned', 'Returned'), ('In Cart', 'In Cart')], default='In progress', max_length=16),
        ),
    ]
