# Generated by Django 3.1.2 on 2021-01-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20210117_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='chosen_size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
