# Generated by Django 3.1.2 on 2021-04-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20210401_0558'),
        ('marketplace', '0002_auto_20210405_1940'),
    ]

    operations = [
    ]
