# Generated by Django 3.1.2 on 2021-04-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourplatform', '0002_auto_20210420_1000'),
        ('github_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubandproject',
            name='repo_owner',
            field=models.CharField(default='me', max_length=255),
        ),
        migrations.AddField(
            model_name='githubandproject',
            name='webhook_id',
            field=models.CharField(default='id', max_length=255),
        ),
        migrations.AlterField(
            model_name='githubandproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourplatform.project', unique=True),
        ),
    ]
