# Generated by Django 3.1.2 on 2020-10-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201022_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_team_lead',
        ),
    ]
