# Generated by Django 3.1.2 on 2020-11-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
