# Generated by Django 3.1.2 on 2021-02-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackevents_sp', '0002_slackprofile_slackprofilecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelcode',
            name='channel_name',
            field=models.CharField(default='Slack channel', max_length=255),
        ),
        migrations.AddField(
            model_name='channelproject',
            name='channel_name',
            field=models.CharField(default='Slack channel', max_length=255),
        ),
        migrations.AddField(
            model_name='slackprofile',
            name='profile_name',
            field=models.CharField(default='Slack profile', max_length=255),
        ),
        migrations.AddField(
            model_name='slackprofilecode',
            name='profile_name',
            field=models.CharField(default='Slack profile', max_length=255),
        ),
    ]
